import { c as create_ssr_component, b as add_attribute, e as escape, f as each } from "../../../../chunks/ssr.js";
import { a as apiURL } from "../../../../chunks/index.js";
import { S as SpotifyLogo, D as DeezerLogo, A as AppleMusicLogo, Y as YTMusicLogo, a as YoutubeLogo, b as AmazonMusicLogo } from "../../../../chunks/YTMusicLogo.js";
const InstagramLogo = "/_app/immutable/assets/InstagramLogo.8345df10.webp";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  console.log(data.artist);
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  return `<div class="w-screen justify-center items-center grid grid-flow-row-dense h-[calc(100vh-8rem)] md:h-[calc(100vh-4rem)]"><div class="relative"><img${add_attribute("src", apiURL + "files/" + data.artist.collectionId + "/" + data.artist.id + "/" + data.artist.Banner, 0)} class="absolute -z-20 h-[calc(100vh-8rem)] md:h-[calc(100vh-4rem)] w-screen object-cover object-top" alt="artistbanner"> <div class="h-[calc(100vh-8rem)] md:h-[calc(100vh-4rem)] w-screen flex justify-center items-center flex-col"><h1 class="text-4xl text-center text-white text-shadow-lg shadow-black">${escape(data.artist.Name)}</h1> <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 p-4 justify-between items-center"><a${add_attribute("href", data.artist.Spotify, 0)}><img${add_attribute("src", SpotifyLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.Deezer, 0)}><img${add_attribute("src", DeezerLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.Apple, 0)}><img${add_attribute("src", AppleMusicLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.YoutubeMusic, 0)}><img${add_attribute("src", YTMusicLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.Youtube, 0)}><img${add_attribute("src", YoutubeLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.Amazon, 0)}><img${add_attribute("src", AmazonMusicLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a> <a${add_attribute("href", data.artist.Instagram, 0)}><img${add_attribute("src", InstagramLogo, 0)} class="aspect-square h-20 p-4 saturate-0 brightness-150" alt="Spotify"></a></div></div></div> <div class="p-8 text-white"><h1 class="text-4xl text-center text-white p-8 pt-0" data-svelte-h="svelte-1h8n6qb">Bio</h1> <p><!-- HTML_TAG_START -->${data.artist.Bio}<!-- HTML_TAG_END --></p></div> <div class="h-[calc(100vh-8rem)] md:h-[calc(100vh-4rem)] p-8 text-white"><h1 class="text-4xl text-center text-white p-8 pt-0" data-svelte-h="svelte-98o1id">Releases</h1> <div class="grid grid-cols-1 lg:grid-cols-2 p-2">${each(data.artist.expand.Releases, (release) => {
    return `<div class="p-2"><iframe${add_attribute("src", release.SpotifyEmbed, 0)} width="100%" height="352" frameborder="0" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" class="w-full" title="miniplayer"></iframe> </div>`;
  })}</div></div></div>`;
});
export {
  Page as default
};
