import { c as create_ssr_component, b as add_attribute, e as escape, f as each } from "../../../../chunks/ssr.js";
import { S as SpotifyLogo, A as AppleMusicLogo, b as AmazonMusicLogo, D as DeezerLogo, Y as YTMusicLogo, a as YoutubeLogo } from "../../../../chunks/YTMusicLogo.js";
import { a as apiURL } from "../../../../chunks/index.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  console.log(data);
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  return `<div class="flex flex-col"><div class="flex p-8 items-center justify-center flex-col lg:flex-row sm:justify-start"><img${add_attribute("src", apiURL + "files/" + data.release.collectionId + "/" + data.release.id + "/" + data.release.Cover, 0)} class="aspect-square relative sm:h-80" alt="artistprofilepicture"> <div class="flex justify-start flex-col items-start p-8 lg:py-0 align-text-bottom lg:self-end font-sans"><p class="text-2xl text-white">${escape(data.release.Name)}</p> ${each(data.release.expand.Artist, (artist) => {
    return `<a href="${"/artist/" + escape(artist.id, true)}" class="text-xl text-gray-400 font-thin underline">${escape(artist.Name)}</a>`;
  })}</div></div> <div class="p-4"><p class="text-white font-sans text-center text-2xl pb-4" data-svelte-h="svelte-l8qd7n">Available Now On:</p> <div class="grid grid-cols-2 md:grid-cols-4 justify-center items-center justify-items-center"><div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.Spotify, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-1bdp7uy"><img${add_attribute("src", SpotifyLogo, 0)} class="aspect-square h-8 w-8" alt="Spotify"> <p class="text-white font-sans text-center">Spotify</p></div></a></div> <div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.Apple, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-2s2u8r"><img${add_attribute("src", AppleMusicLogo, 0)} class="aspect-square h-8 w-8" alt="Apple"> <p class="text-white font-sans text-center">Apple</p></div></a></div> <div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.Amazon, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-1qknp2b"><img${add_attribute("src", AmazonMusicLogo, 0)} class="aspect-square h-8 w-8" alt="Amazon"> <p class="text-white font-sans text-center">Amazon</p></div></a></div> <div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.Deezer, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-1g0vsg7"><img${add_attribute("src", DeezerLogo, 0)} class="aspect-square h-8 w-8" alt="Deezer"> <p class="text-white font-sans text-center">Deezer</p></div></a></div> <div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.YoutubeMusic, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-oeoxek"><img${add_attribute("src", YTMusicLogo, 0)} class="aspect-square h-8 w-8" alt="YTMusic"> <p class="text-white font-sans text-center">YTMusic</p></div></a></div> <div class="p-4"><a class="flex flex-col bg-neutral-950 p-8 rounded-xl w-min justify-center items-center aspect-square h-32"${add_attribute("href", data.release.Youtube, 0)}><div class="flex flex-col justify-center items-center" data-svelte-h="svelte-4n9d17"><img${add_attribute("src", YoutubeLogo, 0)} class="aspect-square h-8 w-8" alt="Youtube"> <p class="text-white font-sans text-center">YouTube</p></div></a></div></div></div></div>`;
});
export {
  Page as default
};
